services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./public:/public
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - PROXY_PORT=8081
      - REVERSE_PROXY_HOST=100.93.190.2.nip.io:8081
    networks:
      - deploy-engine-network
  
networks:
  deploy-engine-network:
    name: deploy-engine-network